### ISSUE TITLE
Add new support for RISC-V architecture

### ISSUE THREAD

**Issue by owlxiao** [avast/capstone-dumper#3]
Hello, I am now trying to add a new architecture support for risc-v. But capstone's risc-v support is in the capstone-next branch, which is inconsistent with the capstone dependency of this item. what should I do?

**Comment by PeterMatula** [comment]
You may change the Capstone dependency in your fork/pull request to the branch (commit) if you need. Simply modify the hash [here](https://github.com/avast/capstone-dumper/blob/master/deps/capstone/CMakeLists.txt#L4).

I'm a bit confused by the Capstone branches/versioning, and so we stuck with that commit which had everything we needed, but if it is blocking you, I see no reason not to update it in order to add new functionality.

One thing though, we don't have any tests you may break by doing this, but it is possible that some of the already implemented architectures are different in the `next` branch and the code itself will break once you change the commit reference. If that happens, I think it should be relatively straightforward to figure out what changed and fix it. But who knows, maybe it will require a lot of updates like in [here](https://github.com/avast/capstone-dumper/commit/bfedf0e81b69c43ca27d510f6cc84a6e3d6234e9). If you have any troubles, let me know, I may be able to help.

**Comment by PeterMatula** [comment]
I will close it now, as the original question was answered, and if I don't do it I will probably forget about it and it will stay open for a long time.
If you however have further questions or need assistance, feel free to reopen it and continue in the discussion.
